name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Use the official PPC toolchain image
    container:
      image: devkitpro/devkitppc:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Wii toolchain & libs via dkp-pacman
        run: |
          # wii-dev brings in devkitppc, libogc, etc.
          dkp-pacman -S --noconfirm wii-dev
          # image/font/FAT support
          dkp-pacman -S --noconfirm \
            ppc-libpng \
            ppc-freetype \
            ppc-libjpeg-turbo \
            libfat-ogc

      - name: Clone GRRLIB
        run: git clone https://github.com/GRRLIB/GRRLIB.git

      - name: Build & install GRRLIB
        run: make -C GRRLIB clean all install

      - name: Build homebrew via Make
        run: make

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: wii-homebrew
          path: |
            build/*.elf
            build/*.dol
